"""Add all current tables

Revision ID: 89207c2d8fc5
Revises: 051e1cce6ef0
Create Date: 2025-05-22 03:59:22.551872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89207c2d8fc5'
down_revision: Union[str, None] = '051e1cce6ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'menu_items', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_items', type_='unique')
    # ### end Alembic commands ###
