"""Add all current tables

Revision ID: b6fea5c6d227
Revises: c72bcc1e7763
Create Date: 2025-05-22 04:13:29.476369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6fea5c6d227'
down_revision: Union[str, None] = 'c72bcc1e7763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('sub_category', sa.Enum('veg', 'non_veg', 'vegan', 'gluten_free', 'soft_drink', 'hot_beverage', 'mocktail', 'cocktail', 'alcohol', name='subcategoryenum'), nullable=True))
    op.drop_column('menu_items', 'subcategory')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('subcategory', postgresql.ENUM('veg', 'non_veg', 'vegan', 'gluten_free', 'soft_drink', 'hot_beverage', 'mocktail', 'cocktail', 'alcohol', name='subcategoryenum'), autoincrement=False, nullable=True))
    op.drop_column('menu_items', 'sub_category')
    # ### end Alembic commands ###
